# Generated by Django 4.0.5 on 2022-09-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload',
            field=models.FileField(default='none', upload_to='uploads/'),
        ),
    ]
